import { ArrowUpRight, History as HistoryIcon, ShieldCheck, Trash2 } from 'lucide-react'
import { useState } from 'react'
import type { HistoryEntry } from '../lib/types'
import { number } from '../lib/format'
export function History({ entries, enabled, toggle, remove, clear, onOpen }: { entries: HistoryEntry[]; enabled: boolean; toggle: () => void; remove: (id: string) => void; clear: () => void; onOpen: (entry: HistoryEntry) => void }) {
  const [confirm, setConfirm] = useState(false)
  return <section className="history-page"><div className="history-preference"><ShieldCheck size={24} /><div><h2>Un historial que tú controlas.</h2><p>Hasta 20 análisis en este navegador. Los textos guardados serán accesibles para quien use este perfil. Desactivarlo detiene nuevos guardados; puedes borrar los anteriores.</p></div><label className="toggle-label"><input type="checkbox" role="switch" checked={enabled} onChange={toggle} /><span>Guardar historial</span></label></div><div className="history-heading"><h2>Textos recientes <span>{entries.length}</span></h2>{entries.length > 0 && <div>{confirm ? <><span className="small">¿Borrar todos?</span><button className="text-button danger-text" onClick={() => { clear(); setConfirm(false) }}>Sí, borrar</button><button className="text-button" onClick={() => setConfirm(false)}>Cancelar</button></> : <button className="text-button" onClick={() => setConfirm(true)}><Trash2 size={14} />Borrar historial</button>}</div>}</div>
    {entries.length ? <ul className="history-list">{entries.map(entry => <li key={entry.id}><button className="history-open" onClick={() => onOpen(entry)}><span className="history-file"><HistoryIcon size={20} /></span><span><strong>{entry.title}</strong><small>{new Date(entry.date).toLocaleString('es-SV', { dateStyle: 'medium', timeStyle: 'short' })} · {number(entry.wordCount)} palabras · {entry.tone}</small><span className="history-excerpt">{entry.text.slice(0, 120)}</span></span><ArrowUpRight size={18} /></button><button className="icon-button" aria-label={`Eliminar ${entry.title}`} onClick={() => remove(entry.id)}><Trash2 size={16} /></button></li>)}</ul> : <div className="compare-empty"><HistoryIcon size={30} /><h3>Las palabras dejan huella.</h3><p>{enabled ? 'Tu próximo análisis aparecerá aquí.' : 'Activa el historial para volver a tus próximos análisis.'}<br />Solo tú decides qué conservar.</p></div>}
  </section>
}
